include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - avoid_classes_with_only_static_members
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_setters_without_getters
    - directives_ordering
    - prefer_const_constructors
    - use_setters_to_change_properties