include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    overridden_fields: ignore
    prefer_const_constructors_in_immutables: ignore
    use_key_in_widget_constructors: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_classes_with_only_static_members
    - avoid_positional_boolean_parameters
    - directives_ordering
    - prefer_single_quotes
