name: xeonjia
description: Save the world by solving ice puzzles and defeating enemies.

version: 2.3.0+13

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: 3.7.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animated_background: 2.0.0
  archive: 3.3.6
  collection: 1.17.0
  device_info_plus: 8.1.0
  flame: 1.6.0
  flame_audio: 1.4.0
  i18n_extension: 6.0.0
  meta: 1.8.0
  path: 1.8.2
  shared_preferences: 2.0.17
  url_launcher: 6.1.9
  window_manager: 0.3.1
  xml: 6.2.2

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/bgm/
    - assets/audio/sfx/
    - assets/data/
    - assets/graphics/
    - assets/images/
    - assets/images/metadata/
    - assets/maps/
    - assets/maps/arena/
    - assets/maps/story/
    - assets/maps/tilesets/
    - locale/be/LC_MESSAGES/
    - locale/bn/LC_MESSAGES/
    - locale/de/LC_MESSAGES/
    - locale/es/LC_MESSAGES/
    - locale/fr/LC_MESSAGES/
    - locale/hu/LC_MESSAGES/
    - locale/id/LC_MESSAGES/
    - locale/it/LC_MESSAGES/
    - locale/ja/LC_MESSAGES/
    - locale/ru/LC_MESSAGES/
    - locale/tr/LC_MESSAGES/
    - locale/uk/LC_MESSAGES/
    - locale/vi/LC_MESSAGES/
    - locale/zh-Hans/LC_MESSAGES/

  fonts:
    - family: dd5x7
      fonts:
        - asset: assets/fonts/dd5x7.ttf
    - family: LanaPixel
      fonts:
        - asset: assets/fonts/LanaPixel.ttf
    - family: kobi
      fonts:
        - asset: assets/fonts/kobi-linear.ttf
