name: xeonjia
description: Save the world by solving ice puzzles and defeating enemies.

version: 3.0.4+21

environment:
  sdk: ">=3.13.1 <4.0.0"
  flutter: 3.47.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animated_background: 2.0.0
  archive: ^4.2.0
  collection: ^1.19.1
  device_info_plus: ^13.2.0
  flame: ^1.38.0
  flame_audio: ^2.12.2
  flame_noise: ^0.3.3+22
  i18n_extension: ^15.1.1
  i18n_extension_importer: ^0.0.6
  meta: ^1.17.0
  path: ^1.9.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  window_manager: ^0.5.2
  xml: ^7.0.1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/bgm/
    - assets/audio/sfx/
    - assets/data/
    - assets/graphics/
    - assets/images/
    - assets/images/metadata/
    - assets/maps/
    - assets/maps/story/
    - assets/maps/tilesets/
    - locale/be/LC_MESSAGES/
    - locale/bn/LC_MESSAGES/
    - locale/de/LC_MESSAGES/
    - locale/es/LC_MESSAGES/
    - locale/fr/LC_MESSAGES/
    - locale/hak/LC_MESSAGES/
    - locale/hu/LC_MESSAGES/
    - locale/id/LC_MESSAGES/
    - locale/it/LC_MESSAGES/
    - locale/ja/LC_MESSAGES/
    - locale/kk/LC_MESSAGES/
    - locale/nn/LC_MESSAGES/
    - locale/pl/LC_MESSAGES/
    - locale/pt-BR/LC_MESSAGES/
    - locale/ru/LC_MESSAGES/
    - locale/tr/LC_MESSAGES/
    - locale/uk/LC_MESSAGES/
    - locale/vi/LC_MESSAGES/
    - locale/zh-Hans/LC_MESSAGES/
    - locale/zh-Hant/LC_MESSAGES/

  fonts:
    - family: dd5x7
      fonts:
        - asset: assets/fonts/dd5x7.ttf
    - family: LanaPixel
      fonts:
        - asset: assets/fonts/LanaPixel.ttf
    - family: kobi
      fonts:
        - asset: assets/fonts/kobi-linear.ttf
