name: xeonjia
description: Solve ice puzzles and defeat enemies in an RPG world.

version: 1.2.0+5

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ^1.19.0-4.2.pre

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.23.0
  url_launcher: ^5.4.11
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/maps/
    - assets/maps/arena/
    - assets/maps/rooms/
