// Language code : language name
const languageName = {
  'en': ['English', 'English'],
  'it': ['Italian', 'Italiano'],
  'es': ['Spanish', 'Español'],
  'fr': ['French', 'Français'],
  'hu': ['Hungarian', 'Magyar'],
  'de': ['German', 'Deutsch'],
  'zh': ['Chinese (Simplified)', '简体中文 (ALPHA)'],
  'vi': ['Vietnamese', 'Tiếng Việt'],
  'uk': ['Ukrainian', 'Українська (ALPHA)'],
  'ar': ['Arabic', 'العربية'],
  'pt': ['Portuguese', 'Português'],
  'ru': ['Russian', 'Русский'],
  'ja': ['Japanese', '日本語'],
  'ko': ['Korean', '한국어'],
  'tr': ['Turkish', 'Türkçe'],
  'pl': ['Polish', 'Polski'],
  'nl': ['Dutch', 'Nederlands'],
  'el': ['Greek', 'Ελληνικά'],
  'no': ['Norwegian', 'Norsk'],
  'da': ['Danish', 'Dansk'],
  'fi': ['Finnish', 'Suomi'],
  'eo': ['Esperanto', 'Esperanto'],
  'id': ['Indonesian', 'Indonesian (ALPHA)'],
  'ia': ['Interlingua', 'Interlingua'],
};
